require "./app"
require 'sinatra/activerecord'
require 'sinatra/activerecord/rake'

Dir["./app/**/*.rb"].each { |file| require file }

namespace :db do
  task :load_config do
    require File.expand_path('../app', __FILE__)
  end
end